/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as SitemapIndexDotxmlRouteImport } from './routes/sitemap-index[.]xml'
import { Route as ApiPostsDotjsonRouteImport } from './routes/api/posts[.]json'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogPostRouteImport } from './routes/blog.$post'
import { Route as SnippetsIndexRouteImport } from './routes/snippets.index'
import { Route as SnippetsSlugRouteImport } from './routes/snippets.$slug'
import { Route as ToolsIndexRouteImport } from './routes/tools.index'
import { Route as ToolsCategoryRouteImport } from './routes/tools.$category'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapIndexDotxmlRoute = SitemapIndexDotxmlRouteImport.update({
  id: '/sitemap-index.xml',
  path: '/sitemap-index.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPostsDotjsonRoute = ApiPostsDotjsonRouteImport.update({
  id: '/api/posts.json',
  path: '/api/posts.json',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogPostRoute = BlogPostRouteImport.update({
  id: '/blog/$post',
  path: '/blog/$post',
  getParentRoute: () => rootRouteImport,
} as any)
const SnippetsIndexRoute = SnippetsIndexRouteImport.update({
  id: '/snippets/',
  path: '/snippets/',
  getParentRoute: () => rootRouteImport,
} as any)
const SnippetsSlugRoute = SnippetsSlugRouteImport.update({
  id: '/snippets/$slug',
  path: '/snippets/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsCategoryRoute = ToolsCategoryRouteImport.update({
  id: '/tools/$category',
  path: '/tools/$category',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap-index.xml': typeof SitemapIndexDotxmlRoute
  '/api/posts.json': typeof ApiPostsDotjsonRoute
  '/blog/$post': typeof BlogPostRoute
  '/snippets/$slug': typeof SnippetsSlugRoute
  '/tools/$category': typeof ToolsCategoryRoute
  '/blog/': typeof BlogIndexRoute
  '/snippets/': typeof SnippetsIndexRoute
  '/tools/': typeof ToolsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap-index.xml': typeof SitemapIndexDotxmlRoute
  '/api/posts.json': typeof ApiPostsDotjsonRoute
  '/blog/$post': typeof BlogPostRoute
  '/snippets/$slug': typeof SnippetsSlugRoute
  '/tools/$category': typeof ToolsCategoryRoute
  '/blog': typeof BlogIndexRoute
  '/snippets': typeof SnippetsIndexRoute
  '/tools': typeof ToolsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap-index.xml': typeof SitemapIndexDotxmlRoute
  '/api/posts.json': typeof ApiPostsDotjsonRoute
  '/blog/$post': typeof BlogPostRoute
  '/snippets/$slug': typeof SnippetsSlugRoute
  '/tools/$category': typeof ToolsCategoryRoute
  '/blog/': typeof BlogIndexRoute
  '/snippets/': typeof SnippetsIndexRoute
  '/tools/': typeof ToolsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/robots.txt'
    | '/rss.xml'
    | '/sitemap-index.xml'
    | '/api/posts.json'
    | '/blog/$post'
    | '/snippets/$slug'
    | '/tools/$category'
    | '/blog/'
    | '/snippets/'
    | '/tools/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/robots.txt'
    | '/rss.xml'
    | '/sitemap-index.xml'
    | '/api/posts.json'
    | '/blog/$post'
    | '/snippets/$slug'
    | '/tools/$category'
    | '/blog'
    | '/snippets'
    | '/tools'
  id:
    | '__root__'
    | '/'
    | '/robots.txt'
    | '/rss.xml'
    | '/sitemap-index.xml'
    | '/api/posts.json'
    | '/blog/$post'
    | '/snippets/$slug'
    | '/tools/$category'
    | '/blog/'
    | '/snippets/'
    | '/tools/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  SitemapIndexDotxmlRoute: typeof SitemapIndexDotxmlRoute
  ApiPostsDotjsonRoute: typeof ApiPostsDotjsonRoute
  BlogPostRoute: typeof BlogPostRoute
  SnippetsSlugRoute: typeof SnippetsSlugRoute
  ToolsCategoryRoute: typeof ToolsCategoryRoute
  BlogIndexRoute: typeof BlogIndexRoute
  SnippetsIndexRoute: typeof SnippetsIndexRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-index.xml': {
      id: '/sitemap-index.xml'
      path: '/sitemap-index.xml'
      fullPath: '/sitemap-index.xml'
      preLoaderRoute: typeof SitemapIndexDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/posts.json': {
      id: '/api/posts.json'
      path: '/api/posts.json'
      fullPath: '/api/posts.json'
      preLoaderRoute: typeof ApiPostsDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$post': {
      id: '/blog/$post'
      path: '/blog/$post'
      fullPath: '/blog/$post'
      preLoaderRoute: typeof BlogPostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snippets/': {
      id: '/snippets/'
      path: '/snippets'
      fullPath: '/snippets/'
      preLoaderRoute: typeof SnippetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snippets/$slug': {
      id: '/snippets/$slug'
      path: '/snippets/$slug'
      fullPath: '/snippets/$slug'
      preLoaderRoute: typeof SnippetsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/$category': {
      id: '/tools/$category'
      path: '/tools/$category'
      fullPath: '/tools/$category'
      preLoaderRoute: typeof ToolsCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  SitemapIndexDotxmlRoute: SitemapIndexDotxmlRoute,
  ApiPostsDotjsonRoute: ApiPostsDotjsonRoute,
  BlogPostRoute: BlogPostRoute,
  SnippetsSlugRoute: SnippetsSlugRoute,
  ToolsCategoryRoute: ToolsCategoryRoute,
  BlogIndexRoute: BlogIndexRoute,
  SnippetsIndexRoute: SnippetsIndexRoute,
  ToolsIndexRoute: ToolsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
